Add download check for docker-compose

diff --git a/zero-lliurex-docker.install/usr/share/zero-lliurex-docker/docker_script b/zero-lliurex-docker.install/usr/share/zero-lliurex-docker/docker_script
--- a/zero-lliurex-docker.install/usr/share/zero-lliurex-docker/docker_script
+++ b/zero-lliurex-docker.install/usr/share/zero-lliurex-docker/docker_script
@@ -31,15 +31,23 @@ case $ACTION in
 		    echo "Skipping docker-compose installation..."
 		else
 		    echo "[EPI]:Installing docker-compose from github..."
-		    TAG="$(curl -s "https://github.com/docker/compose/releases/latest" | sed -nr 's@.*releases/tag/([1-9]+(\.[0-9]+)*)".*@\1@p')"
+		    TAG="$(curl -sSL "https://github.com/docker/compose/releases/latest" | sed -nr 's@.*releases/tag/([1-9]+(\.[0-9]+)*)".*@\1@p' | tr ' ' '\n'|sort -n|uniq|tail -1)"
+		    nTAG="$(echo ${TAG}|wc -w)"
+		    if [ -z "${nTAG}" -o "x${nTAG}" != "x1" ];then
+		        echo "[EPI]:fail installing docker-compose! from tag"
+		        exit 1
+		    fi
 		    if [ -n "${TAG}" ]; then
 			echo "[EPI]:Downloading docker-compose version ${TAG}"
-			curl -sL "https://github.com/docker/compose/releases/download/${TAG}/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
+			curl -sSL "https://github.com/docker/compose/releases/download/${TAG}/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose
 		    fi
 		    if [ -f "/tmp/docker-compose" -a -n "$(file /tmp/docker-compose|grep -o 'ELF 64-bit')" ]; then
 			mv /tmp/docker-compose /usr/bin/docker-compose
 			chmod +x /usr/bin/docker-compose
 			echo "[EPI]:docker-compose installed!"
+		    else
+		        echo "[EPI]:fail installing docker-compose!"
+		        exit 1
 		    fi
 		fi
 	;;
